# Generated by Django 5.2.1 on 2025-06-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicosEssenciais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.TextField(default='<i class="fa-solid fa-laptop"></i>', help_text='Cole um ícone do Fontawesome ou código SVG', verbose_name='Ícone')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título do cartão')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Vantagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.TextField(default='<i class="fa-solid fa-laptop"></i>', help_text='Cole um ícone do Fontawesome ou código SVG', verbose_name='Ícone')),
                ('nome_vantagem', models.CharField(help_text='Exemplo: instalação grátis', max_length=50, verbose_name='Nome da vantagem/serviço incluído')),
            ],
        ),
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.TextField(default='<i class="fa-solid fa-laptop"></i>', help_text='Cole um ícone do Fontawesome ou código SVG', verbose_name='Ícone')),
                ('categoria', models.CharField(help_text='Exemplo: Básico', max_length=100, verbose_name='Categoria')),
                ('velocidade', models.CharField(max_length=100, verbose_name='Velocidade')),
                ('destaque', models.BooleanField(default=False, help_text='marque esta opção se deseja destacar algum plano')),
                ('download', models.CharField(help_text='Exemplo: 200MEGA', max_length=100, verbose_name='Download')),
                ('upload', models.CharField(help_text='Exemplo: 100MEGA', max_length=100, verbose_name='Upload')),
                ('vantagens', models.ManyToManyField(help_text='Escolha as vantagens incluídas neste plano', related_name='planos', to='lgnet_app.vantagens')),
            ],
        ),
    ]
