# Generated by Django 5.2.1 on 2025-06-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0002_planos_criado_em_planos_ultima_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='destaque',
            field=models.BooleanField(default=False, help_text='marque esta opção se deseja destacar o plano'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='icone',
            field=models.TextField(default='<i class="fa-solid fa-laptop"></i>', help_text='Cole um ícone do FontAwesome ou código SVG', verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='servicosessenciais',
            name='icone',
            field=models.TextField(default='<i class="fa-solid fa-laptop"></i>', help_text='Cole um ícone do FontAwesome ou código SVG', verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='vantagens',
            name='icone',
            field=models.TextField(default='<i class="fa-solid fa-laptop"></i>', help_text='Cole um ícone do FontAwesome ou código SVG', verbose_name='Ícone'),
        ),
    ]
