# Generated by Django 5.2.1 on 2025-06-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0003_alter_planos_destaque_alter_planos_icone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planos',
            name='velocidade',
        ),
        migrations.AddField(
            model_name='planos',
            name='plano',
            field=models.CharField(default='300MEGA', max_length=100, verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='download',
            field=models.CharField(help_text='Exemplo: 200Mbps', max_length=100, verbose_name='Download'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='upload',
            field=models.CharField(help_text='Exemplo: 100Mbps', max_length=100, verbose_name='Upload'),
        ),
    ]
