# Generated by Django 5.2.1 on 2025-06-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0004_remove_planos_velocidade_planos_plano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planos',
            name='download',
        ),
        migrations.RemoveField(
            model_name='planos',
            name='upload',
        ),
    ]
