# Generated by Django 5.2.1 on 2025-06-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0005_remove_planos_download_remove_planos_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='download',
            field=models.CharField(default='200Mbps', help_text='Exemplo: 200Mbps', max_length=100, verbose_name='Download'),
        ),
        migrations.AddField(
            model_name='planos',
            name='upload',
            field=models.CharField(default='100Mbps', help_text='Exemplo: 100Mbps', max_length=100, verbose_name='Upload'),
        ),
    ]
