# Generated by Django 5.2.1 on 2025-06-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0006_planos_download_planos_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planos',
            name='download',
        ),
        migrations.RemoveField(
            model_name='planos',
            name='upload',
        ),
    ]
