# Generated by Django 5.2.1 on 2025-06-17 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0007_remove_planos_download_remove_planos_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.TextField(default='<i class="fa-solid fa-laptop"></i>', help_text='Cole um ícone do FontAwesome ou código SVG', verbose_name='Ícone')),
                ('velocidade', models.CharField(default='300MEGA', max_length=1000, verbose_name='Velocidade')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.TextField(default='<i class="fa-solid fa-laptop"></i>', help_text='Cole um ícone do FontAwesome ou código SVG', verbose_name='Ícone')),
                ('velocidade', models.CharField(default='300MEGA', max_length=1000, verbose_name='Velocidade')),
            ],
        ),
        migrations.AddField(
            model_name='planos',
            name='download',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='lgnet_app.download'),
        ),
        migrations.AddField(
            model_name='planos',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='lgnet_app.upload'),
        ),
    ]
