# Generated by Django 5.2.1 on 2025-06-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0008_download_upload_planos_download_planos_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da cidade', max_length=100, verbose_name='Nome')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('cep', models.CharField(help_text='58700-000', max_length=10, verbose_name='CEP')),
                ('latitude', models.TextField(verbose_name='Latitude')),
                ('longitude', models.TextField(verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('link', models.TextField(verbose_name='Link da rede social')),
                ('icone', models.TextField(verbose_name='Ícone')),
            ],
        ),
        migrations.AlterModelOptions(
            name='download',
            options={'verbose_name': 'Velocidade - Download', 'verbose_name_plural': 'Velocidade - Download'},
        ),
        migrations.AlterModelOptions(
            name='planos',
            options={'verbose_name': 'Planos', 'verbose_name_plural': 'Planos'},
        ),
        migrations.AlterModelOptions(
            name='servicosessenciais',
            options={'verbose_name': 'Serviços Essenciais', 'verbose_name_plural': 'Serviços Essenciais'},
        ),
        migrations.AlterModelOptions(
            name='upload',
            options={'verbose_name': 'Velocidade - Upload', 'verbose_name_plural': 'Velocidade - Upload'},
        ),
        migrations.AlterModelOptions(
            name='vantagens',
            options={'verbose_name': 'Vantagens', 'verbose_name_plural': 'Vantagens'},
        ),
        migrations.AlterField(
            model_name='download',
            name='icone',
            field=models.TextField(default='<i class="fa-solid fa-download"></i>', help_text='Cole um ícone do FontAwesome ou código SVG', verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='download',
            name='velocidade',
            field=models.CharField(default='300Mbps', max_length=1000, verbose_name='Velocidade'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='icone',
            field=models.TextField(default='<i class="fa-solid fa-upload"></i>', help_text='Cole um ícone do FontAwesome ou código SVG', verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='velocidade',
            field=models.CharField(default='150Mbps', max_length=1000, verbose_name='Velocidade'),
        ),
        migrations.CreateModel(
            name='InformacoesEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=50, verbose_name='Nome da empresa')),
                ('endereco_completo', models.TextField(verbose_name='Endereço completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contato', models.CharField(max_length=100, verbose_name='Telefone')),
                ('redes_sociais', models.ManyToManyField(related_name='info_empresa', to='lgnet_app.redesocial', verbose_name='Redes Sociais')),
            ],
        ),
    ]
