# Generated by Django 5.2.1 on 2025-06-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0010_alter_cidades_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreMais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('link', models.TextField(verbose_name='Link da página')),
            ],
        ),
    ]
