# Generated by Django 5.2.1 on 2025-06-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0011_exploremais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exploremais',
            options={'verbose_name': 'Explore Mais', 'verbose_name_plural': 'Explore Mais'},
        ),
        migrations.AlterField(
            model_name='exploremais',
            name='link',
            field=models.CharField(max_length=20, verbose_name='Rota'),
        ),
    ]
