# Generated by Django 5.2.1 on 2025-07-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0013_banners_cidades_criado_em_cidades_ultima_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidades',
            name='sigla_estado',
            field=models.CharField(default='PB', max_length=4, verbose_name='Sigla do Estado'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='imagem_de_fundo',
            field=models.ImageField(upload_to='banners/', verbose_name='Imagem de Fundo'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='imagem_principal',
            field=models.ImageField(upload_to='banners/', verbose_name='Imagem Principal'),
        ),
    ]
