# Generated by Django 5.2.1 on 2025-07-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0014_cidades_sigla_estado_alter_banners_imagem_de_fundo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidades',
            name='planos',
            field=models.ManyToManyField(help_text='Planos disponíveis nesta cidade', related_name='cidades', to='lgnet_app.planos'),
        ),
    ]
