# Generated by Django 5.2.1 on 2025-07-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0015_cidades_planos'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Definir ordem em que os planos são mostrados. Exemplo: Plano de 100Mb vem primeiro então o número é 1, 200Mb 2 e assim por diante.', verbose_name='Ordem do plano'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='imagem_de_fundo',
            field=models.ImageField(help_text='Pode ser qualquer resolução de imagem mas o ideal é uma altura de 464px para desktop', upload_to='banners/', verbose_name='Imagem de Fundo'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='imagem_principal',
            field=models.ImageField(help_text='Sugestão: Insira uma imagem com resolução 1244px de largura e 464px de altura para desktop', upload_to='banners/', verbose_name='Imagem Principal'),
        ),
    ]
