# Generated by Django 5.2.1 on 2025-07-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0016_planos_ordem_alter_banners_imagem_de_fundo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesempresa',
            name='slogan',
            field=models.CharField(default='', max_length=80, verbose_name='Slogan'),
        ),
    ]
