# Generated by Django 5.2.1 on 2025-07-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0017_informacoesempresa_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploremais',
            name='imagem',
            field=models.ImageField(default=None, upload_to='explorar/', verbose_name='Imagem Principal'),
        ),
    ]
