# Generated by Django 5.2.1 on 2025-07-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0018_exploremais_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploremais',
            name='conteudo_personalizado',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Conteúdo Personalizado'),
        ),
        migrations.AlterField(
            model_name='exploremais',
            name='imagem',
            field=models.ImageField(default=None, upload_to='explorar/', verbose_name='Imagem do Cartão'),
        ),
    ]
