# Generated by Django 5.2.1 on 2025-07-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0019_exploremais_conteudo_personalizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exploremais',
            name='conteudo_personalizado',
        ),
    ]
