# Generated by Django 5.2.1 on 2025-07-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0020_remove_exploremais_conteudo_personalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploremais',
            name='link',
            field=models.TextField(verbose_name='Rota'),
        ),
    ]
