# Generated by Django 5.2.1 on 2025-07-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0021_alter_exploremais_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExploreMais',
        ),
    ]
