# Generated by Django 5.2.1 on 2025-07-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0022_delete_exploremais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planos',
            name='destaque',
        ),
    ]
