# Generated by Django 5.2.1 on 2025-07-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0023_remove_planos_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesempresa',
            name='atuacao',
            field=models.TextField(default='', verbose_name='Atuação'),
        ),
        migrations.AddField(
            model_name='informacoesempresa',
            name='forca',
            field=models.TextField(default='', verbose_name='Força'),
        ),
        migrations.AddField(
            model_name='informacoesempresa',
            name='imagem_sobre',
            field=models.ImageField(blank=True, null=True, upload_to='sobre/', verbose_name='Imagem da Seção sobre'),
        ),
        migrations.AddField(
            model_name='informacoesempresa',
            name='imagem_visao_missao',
            field=models.ImageField(blank=True, null=True, upload_to='sobre/', verbose_name='Imagem da Seção sobre'),
        ),
        migrations.AddField(
            model_name='informacoesempresa',
            name='missao',
            field=models.CharField(default='', max_length=132, verbose_name='Missão da empresa'),
        ),
        migrations.AddField(
            model_name='informacoesempresa',
            name='sobre',
            field=models.TextField(default='', verbose_name='Sobre'),
        ),
        migrations.AddField(
            model_name='informacoesempresa',
            name='valores',
            field=models.TextField(default='', verbose_name='Atuação'),
        ),
        migrations.AddField(
            model_name='informacoesempresa',
            name='visao',
            field=models.CharField(default='', max_length=132, verbose_name='Visão da empresa'),
        ),
    ]
