# Generated by Django 5.2.1 on 2025-07-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0024_informacoesempresa_atuacao_informacoesempresa_forca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.TextField(verbose_name='Ícone')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='informacoesempresa',
            name='valores',
        ),
    ]
