# Generated by Django 5.2.1 on 2025-07-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0025_valores_remove_informacoesempresa_valores'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesempresa',
            name='valores',
            field=models.ManyToManyField(blank=True, null=True, related_name='valores', to='lgnet_app.valores', verbose_name='Valores'),
        ),
    ]
