# Generated by Django 5.2.1 on 2025-07-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0026_informacoesempresa_valores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valores',
            options={'verbose_name': 'Valor', 'verbose_name_plural': 'Valores'},
        ),
        migrations.AlterField(
            model_name='cidades',
            name='latitude',
            field=models.TextField(help_text='Insira a latitude do escritório da LGNET referente a cidade que deseja cadastrar.', verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='cidades',
            name='longitude',
            field=models.TextField(help_text='Insira a longitude do escritório da LGNET referente a cidade que deseja cadastrar.', verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='informacoesempresa',
            name='valores',
            field=models.ManyToManyField(blank=True, related_name='valores', to='lgnet_app.valores', verbose_name='Valores'),
        ),
        migrations.AlterField(
            model_name='valores',
            name='icone',
            field=models.TextField(help_text='Pode ser colocado código fontawesome ou svg', verbose_name='Ícone'),
        ),
    ]
