# Generated by Django 5.2.1 on 2025-08-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0027_alter_valores_options_alter_cidades_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome do escritório')),
                ('endereco', models.TextField(verbose_name='Endereço exato')),
                ('latitude', models.CharField(max_length=20, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=20, verbose_name='Longitude')),
            ],
        ),
        migrations.AlterField(
            model_name='cidades',
            name='latitude',
            field=models.TextField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='cidades',
            name='longitude',
            field=models.TextField(verbose_name='Longitude'),
        ),
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Encerramento')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='lgnet_app.escritorio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('escritorio', 'dia_semana'), name='dia_unico_por_escritorio')],
            },
        ),
    ]
