# Generated by Django 5.2.1 on 2025-08-01 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0028_escritorio_alter_cidades_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escritorio',
            options={'verbose_name': 'Escritorio', 'verbose_name_plural': 'Escritorios'},
        ),
        migrations.AlterModelOptions(
            name='horariofuncionamento',
            options={'verbose_name': 'Horário Funcionamento', 'verbose_name_plural': 'Horário Funcionamento'},
        ),
        migrations.AddField(
            model_name='escritorio',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escritorio',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
        migrations.AddField(
            model_name='horariofuncionamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horariofuncionamento',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
    ]
