# Generated by Django 5.2.1 on 2025-08-02 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0029_alter_escritorio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariofuncionamento',
            name='horario_fim',
        ),
        migrations.RemoveField(
            model_name='horariofuncionamento',
            name='horario_inicio',
        ),
        migrations.AddField(
            model_name='horariofuncionamento',
            name='primeiro_horario_fim',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='Horário de Encerramento do primeiro turno'),
        ),
        migrations.AddField(
            model_name='horariofuncionamento',
            name='primeiro_horario_inicio',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Horário de Início do primeiro turno'),
        ),
        migrations.AddField(
            model_name='horariofuncionamento',
            name='segundo_horario_fim',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Horário de Encerramento do segundo turno'),
        ),
        migrations.AddField(
            model_name='horariofuncionamento',
            name='segundo_horario_inicio',
            field=models.TimeField(default=datetime.time(14, 0), verbose_name='Horário de Início do segundo turno'),
        ),
    ]
