# Generated by Django 5.2.1 on 2025-08-02 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0030_remove_horariofuncionamento_horario_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariofuncionamento',
            name='tem_segundo_turno',
            field=models.BooleanField(default=True, verbose_name='Tem segundo turno?'),
        ),
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='primeiro_horario_fim',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='Horário de Encerramento do 1º turno'),
        ),
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='primeiro_horario_inicio',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Horário de Início do 1º turno'),
        ),
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='segundo_horario_fim',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), null=True, verbose_name='Horário de Encerramento do 2º turno'),
        ),
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='segundo_horario_inicio',
            field=models.TimeField(blank=True, default=datetime.time(14, 0), null=True, verbose_name='Horário de Início do 2º turno'),
        ),
    ]
