# Generated by Django 5.2.1 on 2025-08-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0031_horariofuncionamento_tem_segundo_turno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escritorio',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
