# Generated by Django 5.2.1 on 2025-08-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0032_escritorio_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntasFrequentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
    ]
