# Generated by Django 5.2.1 on 2025-08-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0033_perguntasfrequentes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perguntasfrequentes',
            options={'verbose_name': 'Perguntas Frequentes', 'verbose_name_plural': 'Perguntas Frequentes'},
        ),
    ]
