# Generated by Django 5.2.1 on 2025-08-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0035_auto_20250821_1623'),
    ]

    operations = [
    ]
