# Generated by Django 5.2.1 on 2025-09-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0036_auto_20250821_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesempresa',
            name='img_app_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='sobre/', verbose_name='Imagem da App Mobile'),
        ),
        migrations.AlterField(
            model_name='perguntasfrequentes',
            name='resposta',
            field=models.TextField(verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='perguntasfrequentes',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Pergunta'),
        ),
    ]
