# Generated by Django 5.2.1 on 2025-09-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0037_informacoesempresa_img_app_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='mensagem',
            field=models.TextField(default='d', verbose_name='Mensagem para mandar pelo whatsapp'),
        ),
        migrations.AlterField(
            model_name='informacoesempresa',
            name='imagem_sobre',
            field=models.ImageField(blank=True, null=True, upload_to='sobre/', verbose_name='Imagem 1 da Seção sobre'),
        ),
        migrations.AlterField(
            model_name='informacoesempresa',
            name='imagem_visao_missao',
            field=models.ImageField(blank=True, null=True, upload_to='sobre/', verbose_name='Imagem 2 da Seção sobre'),
        ),
        migrations.AlterField(
            model_name='informacoesempresa',
            name='img_app_mobile',
            field=models.ImageField(blank=True, help_text='Imagens com proporção 9:16 funcionam perfeitamente.', null=True, upload_to='sobre/', verbose_name='Imagem do App Mobile'),
        ),
    ]
