# Generated by Django 5.2.1 on 2025-09-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0038_banners_mensagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesempresa',
            name='link_apple',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Link do app na Apple Store'),
        ),
        migrations.AddField(
            model_name='informacoesempresa',
            name='link_google',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Link do app na Google Play'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='mensagem',
            field=models.TextField(default='', verbose_name='Mensagem para mandar pelo whatsapp'),
        ),
    ]
