# Generated by Django 5.2.1 on 2025-09-09 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgnet_app', '0039_informacoesempresa_link_apple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='imagem_principal_mobile',
            field=models.ImageField(default=django.utils.timezone.now, help_text='Sugestão: Insira uma imagem com resolução px de largura e px de altura para mobile', upload_to='banners/', verbose_name='Imagem Principal Versão Mobile'),
            preserve_default=False,
        ),
    ]
